[project]
name = "chatterbox-tts"
version = "0.1.4"
description = "Chatterbox: Open Source TTS and Voice Conversion by Resemble AI"
readme = "README.md"
requires-python = ">=3.10"
license = {file = "LICENSE"}
authors = [
    {name = "resemble-ai", email = "engineering@resemble.ai"}
]
dependencies = [
    #"numpy>=1.24.0,<1.26.0",
    "numpy>=2.1.0",
    "librosa~=0.11.0",
    "s3tokenizer",
    "torch==2.6.0",
    "torchaudio==2.6.0",
    "transformers==4.46.3",
    "diffusers==0.29.0",
    "einops>=0.8.1",
    "scipy>=1.15.3",
    "ml-dtypes>=0.5.0",
]

[project.urls]
Homepage = "https://github.com/resemble-ai/chatterbox"
Repository = "https://github.com/resemble-ai/chatterbox"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[dependency-groups]
watermark = [
    "resemble-perth==1.0.1",
]
gradio = [
    "gradio==5.44.1",
    "pandas>=2.3.0",
]
japanese = [
    "pykakasi==2.3.0",
]
chinese = [
    "pkuseg==0.0.25",
]
all = [
    "resemble-perth==1.0.1",
    "gradio==5.44.1",
    "pykakasi==2.3.0",
    "pkuseg==0.0.25",
]
